# Generated by Django 5.0.14 on 2026-09-23 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia / Município')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente (Tenant/Município)',
                'verbose_name_plural': 'Clientes (Tenants/Municípios)',
                'db_table': 'cliente',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla (UF)')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Estado')),
            ],
            options={
                'verbose_name': 'Unidade Federativa',
                'verbose_name_plural': 'Unidades Federativas',
                'db_table': 'uf',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Identificador único para login.', max_length=255, unique=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, help_text='LGPD: Usuários desativados têm login bloqueado sem exclusão de dados históricos.', verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica se o usuário pode acessar a área administrativa do Django.', verbose_name='Acesso Administrativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário de Autenticação',
                'verbose_name_plural': 'Usuários de Autenticação',
                'db_table': 'usuario_auth',
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bairros', to='core.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'db_table': 'bairro',
                'ordering': ['nome'],
                'unique_together': {('nome', 'cidade')},
            },
        ),
        migrations.CreateModel(
            name='Documento_Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TERMOS_DE_USO', 'Termos de Uso'), ('POLITICA_PRIVACIDADE', 'Política de Privacidade')], max_length=30, verbose_name='Tipo de Documento')),
                ('versao', models.CharField(help_text="Ex: '1.0', '2.0-2026'", max_length=20, verbose_name='Versão do Documento')),
                ('conteudo', models.TextField(help_text='Texto completo do documento legal aceito pelo usuário.', verbose_name='Conteúdo Textual / Markdown')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se esta versão é a exigida para novos cadastros.', verbose_name='Documento Vigente')),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legais',
                'db_table': 'documento_legal',
                'unique_together': {('tipo', 'versao')},
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro (Rua, Av, etc.)')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(help_text='Formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='core.bairro', verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla (Ex: USP, UNESP, FATEC)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituicoes', to='core.cliente', verbose_name='Cliente / Prefeitura')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituicoes', to='core.endereco', verbose_name='Endereço da Instituição')),
            ],
            options={
                'verbose_name': 'Instituição de Ensino',
                'verbose_name_plural': 'Instituições de Ensino',
                'db_table': 'instituicao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, help_text='Formato: 000.000.000-00. Pode ser nulo quando anonimizado via LGPD.', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('anonimizado', models.BooleanField(default=False, help_text='Indica se os dados identificáveis foram mascarados por solicitação do titular.', verbose_name='Anonimizado (LGPD)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='core.endereco', verbose_name='Endereço Residencial')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pessoa', to=settings.AUTH_USER_MODEL, verbose_name='Credenciais de Acesso')),
            ],
            options={
                'verbose_name': 'Pessoa (Identidade)',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='Número do Registro CNH')),
                ('categoria_cnh', models.CharField(default='D', max_length=5, verbose_name='Categoria CNH')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motoristas', to='core.cliente', verbose_name='Cliente / Prefeitura Vinculada')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='motorista', to='core.pessoa', verbose_name='Pessoa (Identidade)')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'motorista',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo / Função')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administradores', to='core.cliente', verbose_name='Cliente / Prefeitura Administrada')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='administrador', to='core.pessoa', verbose_name='Pessoa (Identidade)')),
            ],
            options={
                'verbose_name': 'Administrador Municipal',
                'verbose_name_plural': 'Administradores Municipais',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Registro_Consentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consentimento_concedido', models.BooleanField(default=True, help_text='Sinalização explícita do titular (Opt-in).', verbose_name='Consentimento Concedido')),
                ('responsavel_legal_cpf', models.CharField(blank=True, help_text='Obrigatório para menores de 18 anos segundo as regras LGPD do AppBus.', max_length=14, null=True, verbose_name='CPF do Responsável Legal')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP da Conexão')),
                ('user_agent', models.TextField(verbose_name='User-Agent do Navegador/App')),
                ('data_consentimento', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Consentimento')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_consentimento', to='core.documento_legal', verbose_name='Documento Legal Vinculado')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos', to='core.pessoa', verbose_name='Pessoa Titular')),
            ],
            options={
                'verbose_name': 'Registro de Consentimento',
                'verbose_name_plural': 'Registros de Consentimento',
                'db_table': 'registro_consentimento',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='core.uf', verbose_name='UF'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matrícula Estudantil')),
                ('status_aprovacao', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20, verbose_name='Status de Aprovação Cadastral')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Avaliação')),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_avaliados', to='core.administrador', verbose_name='Avaliador Responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='core.cliente', verbose_name='Cliente / Prefeitura Conveniada')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='core.instituicao', verbose_name='Instituição de Ensino')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aluno', to='core.pessoa', verbose_name='Pessoa (Identidade)')),
            ],
            options={
                'verbose_name': 'Aluno (Passageiro)',
                'verbose_name_plural': 'Alunos (Passageiros)',
                'db_table': 'aluno',
                'unique_together': {('cliente', 'matricula')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome', 'uf')},
        ),
    ]
