# Generated by Django 5.0.14 on 2026-09-23 23:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca / Fabricante')),
                ('nome', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Modelo de Veículo',
                'verbose_name_plural': 'Modelos de Veículos',
                'db_table': 'modelo_veiculo',
                'ordering': ['marca', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa do Veículo')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade de Passageiros Sentados')),
                ('qr_code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID do QR Code')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onibus', to='core.cliente', verbose_name='Cliente / Prefeitura')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onibus', to='core.modeloveiculo', verbose_name='Modelo do Veículo')),
            ],
            options={
                'verbose_name': 'Ônibus',
                'verbose_name_plural': 'Ônibus',
                'db_table': 'onibus',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Rota')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='core.cliente', verbose_name='Cliente / Prefeitura')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'db_table': 'rota',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(choices=[('ida', 'Casa -> Instituição'), ('volta', 'Instituição -> Casa')], max_length=10, verbose_name='Sentido da Viagem')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20, verbose_name='Status da Viagem')),
                ('data', models.DateField(verbose_name='Data da Viagem')),
                ('hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('hora_fim', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='core.motorista', verbose_name='Motorista')),
                ('onibus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='core.onibus', verbose_name='Ônibus')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='core.rota', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'db_table': 'viagem',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_validacao', models.CharField(choices=[('qr_code_app', 'QR Code (App Aluno)'), ('manual_motorista', 'Manual (Motorista)')], default='qr_code_app', max_length=20, verbose_name='Método de Validação')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horário do Embarque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embarques', to='core.aluno', verbose_name='Aluno')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embarques', to='core.viagem', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Embarque',
                'verbose_name_plural': 'Embarques',
                'db_table': 'embarque',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrevisaoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data Prevista')),
                ('vai_ida', models.BooleanField(default=False, verbose_name='Vai na Ida')),
                ('vai_volta', models.BooleanField(default=False, verbose_name='Vai na Volta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_viagem', to='core.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Previsão de Viagem',
                'verbose_name_plural': 'Previsões de Viagens',
                'db_table': 'previsao_viagem',
                'ordering': ['-data'],
                'unique_together': {('aluno', 'data')},
            },
        ),
        migrations.CreateModel(
            name='RotaInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_parada', models.PositiveIntegerField(verbose_name='Ordem de Parada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rota_instituicoes', to='core.instituicao', verbose_name='Instituição de Ensino')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_instituicoes', to='core.rota', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Instituição da Rota',
                'verbose_name_plural': 'Instituições da Rota',
                'db_table': 'rota_instituicao',
                'ordering': ['ordem_parada'],
                'unique_together': {('rota', 'instituicao')},
            },
        ),
    ]
